name: py310-chapter6-env
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.10
- pytorch=2.0.0
- torchvision=0.15.0
- torchaudio=2.0.0
- pytorch-cuda=11.7
- pip
- pip:
  - azure-ai-ml==1.5.0
  - mlflow==2.2.2
  - azureml-mlflow==1.49.0
  - ipykernel
  - numpy==1.23.5
  - pandas==1.5.3
  - xlrd==2.0.1
  - transformers==4.27.4
  - accelerate==0.18.0